name: ci-flow
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node: [16.x]
    name: Linters
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        name: run lint
        with:
          node-version: 16.14
      - run: yarn install
      - run: yarn run lint
